python source_gen.py
python attribute_experiment.py
cd attribute_scripts
source petrichor_run.sh
source virga_run.sh
python process.py
cd ..
python attribute_experiment_larger.py
cd attribute_scripts
source petrichor_run.sh
source virga_run.sh
cd ..
python attribute_stat_production.py
python pca_production.py
cd attribute_larger
source run_ld.sh
source run_quadruplets.sh
cd ..
python runtime_gen.py
cd runtime_scripts
source petrichor_run.sh
source virga_run.sh
python produce_graph.py
cd ..
python reverse_script.py
cd reverse
source run_all.sh
cd ..
python reverse_analyse.py
